weighted_average_metric_aggregator:
  _target_: nuplan.planning.metrics.aggregator.weighted_average_metric_aggregator.WeightedAverageMetricAggregator
  name: 'weighted_average_metric_aggregator'
  metric_weights:  # Below we list the metrics used in the scenario scoring function and their corresponsing weights to calculate a weighted average score for each scenario,
  # if not specified, the weight is set as default.
    # metric name : metric weight in the weighted average function
    ego_progress_along_expert_route: 5.0 # This metric has the highest weight equal to 5.0 in the weighted average function, its base score can take a value in [0,1] depending on the ratio of ego to expert progress
    time_to_collision: 5.0 # This metric has the highest weight equal to 5.0 in the weighted average function, its base score can be 0 or 1 depending on the minimum time to collision threshold
    speed_limit_violation_statistics: 4.0 # This metric has a weight equal to 4.0 in the weighted average function, its base score can take a value in [0,1] depending on the amount and duration of over-speeding
    ego_is_comfortable_statistics: 2.0 # This metric has the lowest weight equal to 2.0 in the weighted average function, its base score can be 0 or 1 depending on the comfort thresholds on acceleration, jerk and yaw.
    default: 1.0
  file_name: weighted_average_metrics_${now:${date_format}}
  # The scenario score is defined as the weighted average score of the metrics listed above, multiplied by the score of the multiple_metrics below.
  multiple_metrics:
    - ego_at_fault_collisions_with_pedestrians_statistics  # This metric score can be 0 or 1 depending on whether there is an at fault collision with pedestrians
    - ego_at_fault_collisions_with_vehicles_statistics  # This metric score can be 0 or 1 depending on whether there is an at fault collision with vehicles
    - ego_at_fault_collisions_with_bicycles_statistics  # This metric score can be 0 or 1 depending on whether there is an at fault collision with bicycles
    - ego_at_fault_collisions_with_objects_statistics # This metric score can be 0, 0.5 or 1 depending on the number of at fault collisions with objects
    - drivable_area_violation_statistics # This metric score can be 0 or 1 depending on whether ego drives outside the drivable area
    - ego_is_making_progress_statistics # This metric score can be 0 or 1 depending on whether ego makes progress more than a minimum threshold compared to expert's progress
